from enum import Enum, auto


class XsKey(Enum):
    RESOURCE_VARIABLE_DECLARATION = auto()
    RESOURCE_VARIABLE_COUNT = auto()
    RESOURCE_COUNT_DECLARATION = auto()
    RESOURCE_MAX_SPAWN_DECLARATION = auto()
    RESOURCE_MAX_SPAWN_IS_PER_PLAYER_DECLARATION = auto()
    RESOURCE_LOCATION_INJECTION = auto()
    CONFIG_DECLARATION = auto()
