from enum import Enum, auto


class XsKey(Enum):
    RESOURCE_VARIABLE_DECLARATION = auto()
    RESOURCE_VARIABLE_COUNT = auto()
    RESOURCE_COUNT_DECLARATION = auto()
    RESOURCE_MAX_SPAWN_DECLARATION = auto()
    RESOURCE_MAX_SPAWN_IS_PER_PLAYER_DECLARATION = auto()
    RESOURCE_LOCATION_INJECTION = auto()
    RESOURCE_GROUP_NAMES_DECLARATION = auto()

    CONFIG_DECLARATION = auto()

    AFTER_RESOURCE_SPAWN_EVENT = auto()

    XS_ON_INIT_FILE = auto()
    XS_ON_INIT_RULE = auto()

    XS_ON_SUCCESSFUL_SPAWN = auto()
