name: Publish AoE2ScenarioRms 📦 to PyPI and TestPyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/AoE2ScenarioRms/
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3

    - name: Update Versions for publishing
      run: |
           TAG=$(echo $GITHUB_REF_NAME | sed 's|v||')
           sed -i 's|<VERSION_HERE>|'${TAG}'|' $GITHUB_WORKSPACE/pyproject.toml
           sed -i 's|<VERSION_HERE>|'${TAG}'|' $GITHUB_WORKSPACE/AoE2ScenarioRms/version.py

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user

    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

    - name: Publish AoE2ScenarioRms 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # The pypa/gh-action-pypi-publish action sources attestations from the
        # same source, so leaving attestations enabled (the default behavior)
        # for both steps will cause the production PyPI step to fail; however,
        # disabling attestations on the test PyPI step should allow the
        # production PyPI step to succeed
        attestations: false

    - name: Publish AoE2ScenarioRms 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
